src/Entity/CombatePeleador.php
<?php

namespace App\Entity;

use App\Repository\CombatePeleadorRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CombatePeleadorRepository::class)
 */
class CombatePeleador
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Peleador::class, inversedBy="combates")
     * @ORM\JoinColumn(nullable=false)
     */
    private $peleador;

    /**
     * @ORM\ManyToOne(targetEntity=Combate::class, inversedBy="peleadores")
     * @ORM\JoinColumn(nullable=false)
     */
    private $combate;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $ganador;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $round;

    /**
     * @ORM\ManyToOne(targetEntity=Metodo::class, inversedBy="combatesGanados")
     * @ORM\JoinColumn(nullable=true)
     */
    private $metodo;

    /**
     * @ORM\ManyToOne(targetEntity=MetodoEspecifico::class, inversedBy="combatesGanados")
     * @ORM\JoinColumn(nullable=true)
     */
    private $metodoEspecifico;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPeleador(): ?peleador
    {
        return $this->peleador;
    }

    public function setPeleador(?peleador $peleador): self
    {
        $this->peleador = $peleador;

        return $this;
    }

    public function getCombate(): ?combate
    {
        return $this->combate;
    }

    public function setCombate(?combate $combate): self
    {
        $this->combate = $combate;

        return $this;
    }

    public function isGanador(): ?bool
    {
        return $this->ganador;
    }

    public function setGanador(?bool $ganador): self
    {
        $this->ganador = $ganador;

        return $this;
    }

    public function getRound(): ?string
    {
        return $this->round;
    }

    public function setRound(string $round): self
    {
        $this->round = $round;

        return $this;
    }

    public function getMetodo(): ?metodo
    {
        return $this->metodo;
    }

    public function setMetodo(?metodo $metodo): self
    {
        $this->metodo = $metodo;

        return $this;
    }

    public function getMetodoEspecifico(): ?metodoEspecifico
    {
        return $this->metodoEspecifico;
    }

    public function setMetodoEspecifico(?metodoEspecifico $metodoEspecifico): self
    {
        $this->metodoEspecifico = $metodoEspecifico;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Apuesta::class, mappedBy="usuario",orphanRemoval=true)
     */
    private $apuestas;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Apellidos;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Direccion;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Localidad;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $entidad;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $oficina;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $dc;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_cuenta;

    /**
     * @ORM\OneToMany(targetEntity=MovimientosFinancieros::class, mappedBy="usuario", orphanRemoval=true)
     */
    private $movimientos;

    public function __construct()
    {
        $this->apuestas = new ArrayCollection();
        $this->movimientosFinancieros = new ArrayCollection();
        $this->movimientos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Apuesta>
     */
    public function getApuestas(): Collection
    {
        return $this->apuestas;
    }

    public function addApuesta(Apuesta $apuesta): self
    {
        if (!$this->apuestas->contains($apuesta)) {
            $this->apuestas[] = $apuesta;
            $apuesta->setUsuario($this);
        }

        return $this;
    }

    public function removeApuesta(Apuesta $apuesta): self
    {
        if ($this->apuestas->removeElement($apuesta)) {
            // set the owning side to null (unless already changed)
            if ($apuesta->getUsuario() === $this) {
                $apuesta->setUsuario(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, MovimientosFinancieros>
     */
    public function getMovimientosFinancieros(): Collection
    {
        return $this->movimientos;
    }

    public function addMovimientosFinanciero(MovimientosFinancieros $movimientos): self
    {
        if (!$this->movimientos->contains($movimientos)) {
            $this->movimientos[] = $movimientos;
            $movimientos->setUsuario($this);
        }

        return $this;
    }

    public function removeMovimientosFinanciero(MovimientosFinancieros $movimientos): self
    {
        if ($this->movimientos->removeElement($movimientos)) {
            // set the owning side to null (unless already changed)
            if ($movimientos->getUsuario() === $this) {
                $movimientos->setUsuario(null);
            }
        }

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->Apellidos;
    }

    public function setApellidos(string $Apellidos): self
    {
        $this->Apellidos = $Apellidos;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->Direccion;
    }

    public function setDireccion(string $Direccion): self
    {
        $this->Direccion = $Direccion;

        return $this;
    }

    public function getLocalidad(): ?string
    {
        return $this->Localidad;
    }

    public function setLocalidad(string $Localidad): self
    {
        $this->Localidad = $Localidad;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getEntidad(): ?string
    {
        return $this->entidad;
    }

    public function setEntidad(string $entidad): self
    {
        $this->entidad = $entidad;

        return $this;
    }

    public function getOficina(): ?string
    {
        return $this->oficina;
    }

    public function setOficina(string $oficina): self
    {
        $this->oficina = $oficina;

        return $this;
    }

    public function getDc(): ?string
    {
        return $this->dc;
    }

    public function setDc(string $dc): self
    {
        $this->dc = $dc;

        return $this;
    }

    public function getNumeroCuenta(): ?string
    {
        return $this->numero_cuenta;
    }

    public function setNumeroCuenta(string $numero_cuenta): self
    {
        $this->numero_cuenta = $numero_cuenta;

        return $this;
    }

    /**
     * @return Collection<int, MovimientosFinancieros>
     */
    public function getMovimientos(): Collection
    {
        return $this->movimientos;
    }

    public function addMovimiento(MovimientosFinancieros $movimiento): self
    {
        if (!$this->movimientos->contains($movimiento)) {
            $this->movimientos[] = $movimiento;
            $movimiento->setUsuario($this);
        }

        return $this;
    }

    public function removeMovimiento(MovimientosFinancieros $movimiento): self
    {
        if ($this->movimientos->removeElement($movimiento)) {
            // set the owning side to null (unless already changed)
            if ($movimiento->getUsuario() === $this) {
                $movimiento->setUsuario(null);
            }
        }

        return $this;
    }
    public function getSaldo()
    {
        $saldo=0;
        $movimientos=$this->getMovimientos();
        foreach($movimientos as $movimiento){
            $saldo+=$movimiento->getImporte();
        }

        return $saldo;
    }
    
}

src/Form/CombatePeleadorType.php
<?php

namespace App\Form;

use App\Entity\Combate;
use App\Entity\CombatePeleador;
use App\Entity\Metodo;
use App\Entity\MetodoEspecifico;
use App\Entity\Peleador;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CombatePeleadorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ganador',ChoiceType::class, [
                'placeholder' => 'Seleccione',
                'choices'  => [
                    'Si' => true,
                    'No' => false
                ],
                'required' => false
            ])
            ->add('round',ChoiceType::class, [
                'placeholder' => 'Seleccione',
                'choices'  => [
                    '3' => '3',
                    '5' => '5'
                ],
            ])
            ->add('peleador', EntityType::class, [
                'placeholder' => 'Seleccione',
                'class' => Peleador::class,
                'choice_label' => 'nombre',
                ])
            ->add('peleador2', EntityType::class, [
                'placeholder' => 'Seleccione',
                'class' => Peleador::class,
                'choice_label' => 'nombre',
                'mapped' => false
                ])
            ->add('combate', EntityType::class, [
                'placeholder' => 'Seleccione',
                'class' => Combate::class,
                'choice_label' => 'nombre',
                ])
            ->add('metodo', EntityType::class, [
                'placeholder' => 'Seleccione',
                'class' => Metodo::class,
                'choice_label' => 'descripcion',
                'required' => false
                ])
            ->add('metodoEspecifico', EntityType::class, [
                'placeholder' => 'Seleccione',
                'class' => MetodoEspecifico::class,
                'choice_label' => 'descripcion',
                'required' => false
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CombatePeleador::class,
        ]);
    }
}

src/Controller/CombatePeleadorController.php
<?php

namespace App\Controller;

use App\Entity\Combate;
use App\Entity\CombatePeleador;
use App\Entity\Evento;
use App\Form\CombatePeleadorType;
use App\Repository\CombatePeleadorRepository;
use App\Repository\CombateRepository;
use App\Repository\EventoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/combatesPeleador/")
 */
class CombatePeleadorController extends AbstractController
{
    /**
     * @Route("/", name="app_combate_peleador_index", methods={"GET"})
     */
    public function index(Request $request ,CombatePeleadorRepository $combatePeleadorRepository, CombateRepository $combateRepository, EventoRepository $eventoRepository): Response
    {
        $eventoId=$request->attributes->get('id');
        $evento=$eventoRepository->find($eventoId);

        $combates=$combateRepository->findBy(['evento'=> $evento]);

        $peleadores=$combatePeleadorRepository->findPeleadoresCombates($combates);

        return $this->render('combate_peleador/index.html.twig', [
            'peleadores' => $peleadores,
            'evento' => $evento
        ]);
    }

    /**
     * @Route("{id}/new", name="app_combate_peleador_new", methods={"GET", "POST"},requirements={"id":"\d+"})
     */
    public function new(Request $request, CombatePeleadorRepository $combatePeleadorRepository, Combate $combate): Response
    {
        
        $combatePeleador = new CombatePeleador();
        $combatePeleador->setCombate($combate);
        $form = $this->createForm(CombatePeleadorType::class, $combatePeleador);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $combatePeleadorRepository->add($combatePeleador, true);

            return $this->redirectToRoute('app_combate_peleador_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('combate_peleador/new.html.twig', [
            'combate_peleador' => $combatePeleador,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_combate_peleador_show", methods={"GET"})
     */
    public function show(CombatePeleador $combatePeleador): Response
    {
        return $this->render('combate_peleador/show.html.twig', [
            'combate_peleador' => $combatePeleador,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_combate_peleador_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, CombatePeleador $combatePeleador, CombatePeleadorRepository $combatePeleadorRepository): Response
    {
        $form = $this->createForm(CombatePeleadorType::class, $combatePeleador);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $combatePeleadorRepository->add($combatePeleador, true);

            return $this->redirectToRoute('app_combate_peleador_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('combate_peleador/edit.html.twig', [
            'combate_peleador' => $combatePeleador,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_combate_peleador_delete", methods={"POST"})
     */
    public function delete(Request $request, CombatePeleador $combatePeleador, CombatePeleadorRepository $combatePeleadorRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$combatePeleador->getId(), $request->request->get('_token'))) {
            $combatePeleadorRepository->remove($combatePeleador, true);
        }

        return $this->redirectToRoute('app_combate_peleador_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/combate_peleador/_delete_form.html.twig
<form method="post" action="{{ path('app_combate_peleador_delete', {'id': combate_peleador.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ combate_peleador.id) }}">
    <button class="btn">Delete</button>
</form>

templates/combate_peleador/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/combate_peleador/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CombatePeleador{% endblock %}

{% block body %}
    <h1>Edit CombatePeleador</h1>

    {{ include('combate_peleador/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_combate_peleador_index') }}">back to list</a>

    {{ include('combate_peleador/_delete_form.html.twig') }}
{% endblock %}

templates/combate_peleador/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CombatePeleador index{% endblock %}

{% block body %}

<div class="container">
    <section class="normal-breadcrumb set-bg" data-setbg="{{ asset('img/'~ evento.imagen )}}">
        <div class="col-lg-12 text-center">
            <div class="normal__breadcrumb__text">
                <h2>{{evento.nombre}}</h2>
            </div>
        </div>
    </section>
    <br>
    {% for peleador in peleadores %}
    <div class="row">
        <h3 class="text-light">{{peleador.peleador.nombre}} <a href="{{path('app_apuesta_new')}}" class="btn btn-danger btn-lg active" role="button" aria-pressed="true">Apostar</a></h3> 
    </div>
    {% endfor %}
    <a href="{{ path('app_combate_peleador_new') }}">Create new</a>
</div>
    
{% endblock %}

templates/combate_peleador/new.html.twig
<div class="container">
    <section class="normal-breadcrumb set-bg" data-setbg="{{ asset('img/evento.jpg' )}}">
    </section>
    <br>
    {{ form_start(form) }}
    <h2>Crear Evento</h2>
        <div class="form-row">
            <div class ="col">
                <label class="text-white">Nombre</label>
                {{ form_widget(form.nombre, { 'attr': {'class': 'form-control'} } )}}
            </div>
            <div class="col">
                <label class="text-white">Localidad</label>
                {{ form_widget(form.localidad, { 'attr': {'class': 'form-control'}} )}}
            </div>
            <div class ="col">
            </div>
        </div>
        <br>
        <div class="form-row">
            <div class ="col">
                <label class="text-white">Fecha</label>
                {{ form_widget(form.fecha, { 'attr': {'class': 'form-control'} } )}}
            </div>
            <div class ="col">
                <label class="text-white">Imagen</label>
                {{ form_widget(form.imagen, { 'attr': {'class': 'form-control'} } )}}
            </div>
            <div class ="col">
            </div>
        </div>
        <br>
        <div class="row justify-content-md-center">
            <div class="col col-lg-2">
                <button type="submit" class="site-btn">Guardar Cambios</button>
            </div>
            <div class="col col-lg-2">
                <button class="site-btn"><a class= " text-white"href="{{ path('app_apuestas') }}">Volver al inicio</a></button>
            </div>
            <div class="col col-lg-2">
        </div>
    {{ form_end(form, {render_rest: false}) }}
</div>
<br>
<div class='container'>
    <table class="table bg-light">
    <thead style="background-color:#e53637">
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Nombre</th>
        <th scope="col">Localidad</th>
        <th scope="col">Fecha</th>
        <th scope="col">Acciones</th>
    </tr>
    </thead>
    <tbody>
    {% for evento in eventos %}
    <tr>
        <th scope="row">{{evento.id}}</th>
        <td>{{evento.nombre}}</td>
        <td>{{evento.localidad}}</td>
        <td>{{evento.fecha|date("d/m/Y")}}</td>
        <td>
            <button type="button" class="btn btn-success"><i class="fa fa-edit"></i></button>
            <button type="button" class="btn btn-danger"><i class="fa fa-trash"></i></button>
            <button type="button" class="btn btn-info"><a class= "text-white"href="{{ path('app_combate_peleador_new') }}">+</a></button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
</div>

templates/combate_peleador/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CombatePeleador{% endblock %}

{% block body %}
    <h1>CombatePeleador</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ combate_peleador.id }}</td>
            </tr>
            <tr>
                <th>Ganador</th>
                <td>{{ combate_peleador.ganador ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Round</th>
                <td>{{ combate_peleador.round }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_combate_peleador_index') }}">back to list</a>

    <a href="{{ path('app_combate_peleador_edit', {'id': combate_peleador.id}) }}">edit</a>

    {{ include('combate_peleador/_delete_form.html.twig') }}
{% endblock %}