src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Apuesta::class, mappedBy="usuario",orphanRemoval=true)
     */
    private $apuestas;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Apellidos;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Direccion;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Localidad;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $entidad;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $oficina;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $dc;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_cuenta;

    /**
     * @ORM\OneToMany(targetEntity=MovimientosFinancieros::class, mappedBy="usuario", orphanRemoval=true)
     */
    private $movimientos;

    public function __construct()
    {
        $this->apuestas = new ArrayCollection();
        $this->movimientosFinancieros = new ArrayCollection();
        $this->movimientos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Apuesta>
     */
    public function getApuestas(): Collection
    {
        return $this->apuestas;
    }

    public function addApuesta(Apuesta $apuesta): self
    {
        if (!$this->apuestas->contains($apuesta)) {
            $this->apuestas[] = $apuesta;
            $apuesta->setUsuario($this);
        }

        return $this;
    }

    public function removeApuesta(Apuesta $apuesta): self
    {
        if ($this->apuestas->removeElement($apuesta)) {
            // set the owning side to null (unless already changed)
            if ($apuesta->getUsuario() === $this) {
                $apuesta->setUsuario(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, MovimientosFinancieros>
     */
    public function getMovimientosFinancieros(): Collection
    {
        return $this->movimientos;
    }

    public function addMovimientosFinanciero(MovimientosFinancieros $movimientos): self
    {
        if (!$this->movimientos->contains($movimientos)) {
            $this->movimientos[] = $movimientos;
            $movimientos->setUsuario($this);
        }

        return $this;
    }

    public function removeMovimientosFinanciero(MovimientosFinancieros $movimientos): self
    {
        if ($this->movimientos->removeElement($movimientos)) {
            // set the owning side to null (unless already changed)
            if ($movimientos->getUsuario() === $this) {
                $movimientos->setUsuario(null);
            }
        }

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->Apellidos;
    }

    public function setApellidos(string $Apellidos): self
    {
        $this->Apellidos = $Apellidos;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->Direccion;
    }

    public function setDireccion(string $Direccion): self
    {
        $this->Direccion = $Direccion;

        return $this;
    }

    public function getLocalidad(): ?string
    {
        return $this->Localidad;
    }

    public function setLocalidad(string $Localidad): self
    {
        $this->Localidad = $Localidad;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getEntidad(): ?string
    {
        return $this->entidad;
    }

    public function setEntidad(string $entidad): self
    {
        $this->entidad = $entidad;

        return $this;
    }

    public function getOficina(): ?string
    {
        return $this->oficina;
    }

    public function setOficina(string $oficina): self
    {
        $this->oficina = $oficina;

        return $this;
    }

    public function getDc(): ?string
    {
        return $this->dc;
    }

    public function setDc(string $dc): self
    {
        $this->dc = $dc;

        return $this;
    }

    public function getNumeroCuenta(): ?string
    {
        return $this->numero_cuenta;
    }

    public function setNumeroCuenta(string $numero_cuenta): self
    {
        $this->numero_cuenta = $numero_cuenta;

        return $this;
    }

    /**
     * @return Collection<int, MovimientosFinancieros>
     */
    public function getMovimientos(): Collection
    {
        return $this->movimientos;
    }

    public function addMovimiento(MovimientosFinancieros $movimiento): self
    {
        if (!$this->movimientos->contains($movimiento)) {
            $this->movimientos[] = $movimiento;
            $movimiento->setUsuario($this);
        }

        return $this;
    }

    public function removeMovimiento(MovimientosFinancieros $movimiento): self
    {
        if ($this->movimientos->removeElement($movimiento)) {
            // set the owning side to null (unless already changed)
            if ($movimiento->getUsuario() === $this) {
                $movimiento->setUsuario(null);
            }
        }

        return $this;
    }
    public function getSaldo()
    {
        $saldo=0;
        $movimientos=$this->getMovimientos();
        foreach($movimientos as $movimiento){
            $saldo+=$movimiento->getImporte();
        }

        return $saldo;
    }
    
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            ->add('password', RepeatedType::class, [
                'mapped' => false,
                'type' => PasswordType::class,
                'invalid_message' => 'Las contraseñas deben coincidir',
                'options' => ['attr' => ['class' => 'password-field']],
                'required' => true,
                'first_options'  => ['label' => 'Contraseña'],
                'second_options' => ['label' => 'Repite la contraseña'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        'max' => 4096,
                    ]),
                ],
            ])
            ->add('contrasenaActual', PasswordType::class, [
                'mapped' => false,
                'attr' => ['autocomplete' => 'new-password'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
            ->add('Nombre')
            ->add('Apellidos')
            ->add('Direccion')
            ->add('Localidad')
            ->add('email')
            ->add('telefono')
            ->add('entidad')
            ->add('oficina')
            ->add('dc')
            ->add('numero_cuenta')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\MovimientosFinancieros;
use App\Entity\User;
use App\Form\UserType;
use App\Form\CambiarContrasenaType;
use App\Form\MovimientosFinancierosType;
use App\Repository\ApuestaRepository;
use App\Repository\MovimientosFinancierosRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="app_user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_user_new", methods={"GET", "POST"})
     */
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $user = new User();
        $user->setRoles(['ROLE_USER']);
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_user_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, User $user, UserRepository $userRepository, ApuestaRepository $apuestaRepository, MovimientosFinancierosRepository $movimientosFinancierosRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $userRepository->add($user, true);

            return $this->redirectToRoute('app_user_edit', ['id'=>$user->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
            'apuestas' => $apuestaRepository->findByUsuario($user->getId()),
            'movimientos' => $movimientosFinancierosRepository->findByUsuario($user->getId()),
            'saldo'=>$user->getSaldo()
        ]);
    }

    /**
     * @Route("/delete/{id}", name="app_user_delete", methods={"POST","GET"})
     */
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
            $userRepository->remove($user, true);

            $session = $this->get('session');
          $session = new Session();
          $session->invalidate();
          
        return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/{id}/cambiarContrasena", name="app_cambiar_contrasena", methods={"GET", "POST"})
     */
    public function cambiarContrasena(Request $request, User $user, UserRepository $userRepository, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        

        $form = $this->createForm(CambiarContrasenaType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $contrasenas=$request->request->get('cambiar_contrasena');
            if($userPasswordHasher->isPasswordValid($user, $contrasenas['contrasenaActual'])){
                if($contrasenas['password']['first']===$contrasenas['password']['second']){
                    $user->setPassword(
                        $userPasswordHasher->hashPassword(
                                $user,
                                $contrasenas['password']['first']
                            )
                        );
                        $userRepository->add($user, true);
                    $this->addFlash(
                        'success',
                        'Contraseña cambiada correctamente!'
                    ); 
                    return $this->redirectToRoute('app_user_edit', ['id'=>$user->getId()], Response::HTTP_SEE_OTHER);
                }{
                    $this->addFlash(
                        'warning',
                        'Las contraseñas no coinciden!!'
                    ); 
                }
                
            }
            else{
                $this->addFlash(
                    'warning',
                    'Contraseña actual erronea!'
                );      
            }                        
        }

        return $this->renderForm('user/cambiarContrasena.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);

    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="site-btn">Borrar Usuario</button>
</form>

templates/user/_form.html.twig
<div class="container">
    <section class="normal-breadcrumb set-bg" data-setbg="{{ asset('img/usuario.jpeg' )}}">
    </section>
    <div class="container">
        <h3 class="text-white">Datos del usuario</h3>
        {% include '_mensajes.html.twig' %}
        {{ form_start(form) }}
            <div class="form-row">
                <div class ="col">
                    <label class="text-white">Username</label>
                    {{ form_widget(form.username, { 'attr': {'class': 'form-control'} } )}}<br>
                    <button class="site-btn"><a class= "text-white"href="{{ path('app_cambiar_contrasena',{'id': user.id}) }}">Cambiar Contraseña</a></button>

                </div>
                <div class="col"><br>
                </div>
                <div class ="col"><br>
                    <h2 class="text-white">Saldo: {{saldo}}€</h2><br>
                    <button class="site-btn"><a class= "text-white"href="{{ path('app_movimientos_financieros_new') }}">Realizar ingreso </a></button>
                </div>
            </div>
            <br>
            <h3 class="text-white">Datos de contacto</h3>
            <div class="form-row">
                <div class ="col">
                    <label class="text-white">Nombre</label>
                    {{ form_widget(form.Nombre, { 'attr': {'class': 'form-control'} } )}}
                </div>
                <div class ="col">
                    <label class="text-white">Apellidos</label>
                    {{ form_widget(form.Apellidos, { 'attr': {'class': 'form-control'} } )}}
                </div>
                <div class ="col">
                </div>
            </div>
            <br>
            <div class="form-row">
                <div class ="col">
                    <label class="text-white">Direccion</label>
                    {{ form_widget(form.Direccion, { 'attr': {'class': 'form-control'} } )}}
                </div>
                <div class ="col">
                    <label class="text-white">Localidad</label>
                    {{ form_widget(form.Localidad, { 'attr': {'class': 'form-control'} } )}}
                </div>
                <div class ="col">
                    <label class="text-white">Email</label>
                    {{ form_widget(form.email, { 'attr': {'class': 'form-control'} } )}}
                </div>
                <div class ="col">
                    <label class="text-white">Telefono</label>
                    {{ form_widget(form.telefono, { 'attr': {'class': 'form-control'} } )}}
                </div>
            </div>
            <br>
            <h3 class="text-white">Datos bancarios</h3>
            <div class="form-row">
                <div class ="col">
                    <label class="text-white">Entidad</label>
                    {{ form_widget(form.entidad, { 'attr': {'class': 'form-control'} } )}}
                </div>
                <div class ="col">
                    <label class="text-white">Oficina</label>
                    {{ form_widget(form.oficina, { 'attr': {'class': 'form-control'} } )}}
                </div>
                <div class ="col">
                    <label class="text-white">DC</label>
                    {{ form_widget(form.dc, { 'attr': {'class': 'form-control'} } )}}
                </div>
                <div class ="col">
                    <label class="text-white">Numero de cuenta</label>
                    {{ form_widget(form.numero_cuenta, { 'attr': {'class': 'form-control'} } )}}
                </div>
            </div>
            <br>
            <div class="row justify-content-md-center">
                <div class="col col-lg-2">
                    <button type="submit" class="site-btn">Guardar Cambios</button>
                </div>
                <div class="col col-lg-2">
                    <button class="site-btn"><a class= " text-white"href="{{ path('app_apuestas') }}">Volver al inicio</a></button>
                </div>
                <div class="col col-lg-2">
                    <button class="site-btn"><a class= " text-white"href="{{ path('app_user_delete',{'id':app.user.id}) }}">Borrar Usuario</a></button>
                </div>
            </div>
        {{ form_end(form, {render_rest: false}) }}
    </div>
</div>   
<br>
<div class='container'>
    <div class="row">
        <div class="col-sm-8">
        <h2 class="text-white">Apuestas</h2>
            <table class="table bg-light">
                <thead style="background-color:#e53637">
                    <tr>
                        <th scope="col">Id</th>
                        <th>Combate</th>
                        <th>Evento</th>
                        <th>Ganador</th>
                        <th>Round</th>
                        <th>Metodo</th>
                        <th>Metodo Especifico</th>
                        <th>Cantidad(€)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for apuesta in apuestas %}
                    {% if apuesta.cobrada == true %}
                    <tr style="background-color:gold">
                    {% else %}
                    <tr>
                    {% endif %}
                        <th scope="row">{{apuesta.id}}</th>
                        <td>{{apuesta.combate.nombre}}</td>
                        <td>{{apuesta.combate.evento.nombre}}</td>
                        <td>{{apuesta.ganador.nombre}}</td>
                        <td>{{apuesta.round}}</td>
                        {% if apuesta.metodo is null %}
                            <td></td>
                        {% else %}
                            <td>{{apuesta.metodo.descripcion}}</td>
                        {% endif %}
                        {% if apuesta.metodoEspecifico is null %}
                            <td></td>
                        {% else %}
                        <td>{{apuesta.metodoEspecifico.descripcion}}</td>
                        {% endif %}
                        <td>{{apuesta.cantidad}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-sm-4">
        <h2 class="text-white">Movimientos</h2>
            <table class="table bg-light">
                <thead style="background-color:#e53637">
                    <tr>
                        <th scope="col">Id</th>
                        <th>Concepto</th>
                        <th>Importe(€)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for movimiento in movimientos %}
                    <tr>
                        <th scope="row">{{movimiento.id}}</th>
                        <td>{{movimiento.concepto}}</td>
                        <td>{{movimiento.importe}}€</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

templates/user/cambiarContrasena.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <section class="normal-breadcrumb set-bg" data-setbg="{{ asset('img/contrasena.jpg' )}}">
    </section>
        <div class="container">
        <br>
        <h3 class="text-white">Cambiar contraseña del usuario: <b>{{user.username}}</b></h3>
        {% include '_mensajes.html.twig' %}
        <br>
            {{ form_start(form) }}
                <div class="form-row">
                    <div class ="col">
                        <label class="text-white">Contraseña Actual</label>
                        {{ form_widget(form.contrasenaActual, { 'attr': {'class': 'form-control'} } )}}
                    </div>
                    <div class ="col">
                    </div>
                    <div class ="col">
                    </div>
                </div>
                <div class="form-row">
                    <div class ="col">
                        <label class="text-white">Contraseña nueva</label>
                        {{ form_widget(form.password.first, { 'attr': {'class': 'form-control'} } )}}
                    </div>
                    <div class ="col">
                        <label class="text-white">Confirmar contraseña</label>
                        {{ form_widget(form.password.second, { 'attr': {'class': 'form-control'} } )}}
                    </div>
                    <div class ="col">
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col col-lg-2">
                        <button type="submit" class="site-btn">Cambiar contraseña</button>
                    </div>
        {{ form_end(form, {render_rest: false}) }}
                    <div class="col col-lg-2">
                        <button class="site-btn"><a class= " text-white"href="{{ path('app_user_edit',{'id':app.user.id}) }}">Volver atrás</a></button>
                    </div>
                    <div class="col col-lg-2">
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Direccion</th>
                <th>Localidad</th>
                <th>Email</th>
                <th>Telefono</th>
                <th>Entidad</th>
                <th>Oficina</th>
                <th>Dc</th>
                <th>Numero_cuenta</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.Nombre }}</td>
                <td>{{ user.Apellidos }}</td>
                <td>{{ user.Direccion }}</td>
                <td>{{ user.Localidad }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.telefono }}</td>
                <td>{{ user.entidad }}</td>
                <td>{{ user.oficina }}</td>
                <td>{{ user.dc }}</td>
                <td>{{ user.numeroCuenta }}</td>
                <td>
                    <a href="{{ path('app_user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="15">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
<div class="container">
    <section class="normal-breadcrumb set-bg" data-setbg="{{ asset('img/registro.jpg' )}}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="normal__breadcrumb__text">
                        <h2>Registro</h2>
                        <p>Bienvenido a apuestas UFC</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="login spad">
        <div class="container">
            {{ include('user/_form.html.twig') }}
        </div>
    </section>
</div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Username</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ user.Nombre }}</td>
            </tr>
            <tr>
                <th>Apellidos</th>
                <td>{{ user.Apellidos }}</td>
            </tr>
            <tr>
                <th>Direccion</th>
                <td>{{ user.Direccion }}</td>
            </tr>
            <tr>
                <th>Localidad</th>
                <td>{{ user.Localidad }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ user.telefono }}</td>
            </tr>
            <tr>
                <th>Entidad</th>
                <td>{{ user.entidad }}</td>
            </tr>
            <tr>
                <th>Oficina</th>
                <td>{{ user.oficina }}</td>
            </tr>
            <tr>
                <th>Dc</th>
                <td>{{ user.dc }}</td>
            </tr>
            <tr>
                <th>Numero_cuenta</th>
                <td>{{ user.numeroCuenta }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_user_index') }}">back to list</a>

    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}